### ISSUE TITLE
Question about threshold and unknown class weight.

### ISSUE THREAD

**Issue by LeoXinhaoLee** [silvia1993/ROS#7]
Thank you very much for your nice code for this inspiring paper. I notice that there seems to be 2 differences between your code and paper.

1) When dividing target data into 'Known' and 'Unknown', the threshold in the code is slightly different from the mean of the Normality scores of all target samples. Besides, the `select_hight` and `select_low` both equal `num_low`. So what's the reason for this strategy?

2) When using the 'Unknown' target samples to train the classifier, the code adopts `weight_class_unknown = 1/( select_low * ( self.n_classes/(len(source_train_ss)*self.batch_size) ) )`, which seems to be not mentioned in the paper. So what's the benefit for this weight apart from `self.weight_class_unknown=2`?

Thank you for your time and help.

**Comment by silvia1993** [comment]
Hi @LeoXinhaoLee,

thank you for your interest!

I already answer 1. in this previous issue https://github.com/silvia1993/ROS/issues/4

For 2. I use the formula that you mentioned simply to balance the learning of the unknown class with respect to the other known classes. Since the amount of unknown samples selected after Stage1 is much more with respect to the samples-per-class of the known categories, the unknown class could be learned much more than the others causing a bias in the predictions. 
For what concerns the parameter self.weight_class_unknown=2, in Stage2, I start the training using the model trained in Stage1, so the known classes were already learned and so I need to speed up the learning of the unknown class never seen in Stage1.

I hope this clarifies your doubts!

**Comment by LeoXinhaoLee** [comment]
Doubts clarified. Thank you for the concrete answer!
